### ISSUE TITLE
Try to remove --rpc-methods=Unsafe

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/polkadot-failover-mechanism#12]
`--rpc-methods=Unsafe` is not required anymore as for 0.8.1 release to insert keys. We should test this and remove if it is not necessary to improve security.

**Comment by trezorg** [comment]
**With Unsafe**

`
docker run -it --name polcadot --rm -v /tmp:/data:z -p 127.0.0.1:9933:9933 -p 30333:30333 parity/polkadot:master --chain westend --pruning=archive --rpc-methods=Unsafe --rpc-external -d /data
`

`
curl -H 'Content-Type: application/json' -d '{"id":1, "jsonrpc":"2.0", "method": "author_insertKey", "params":["gran","favorite liar zebra assume hurt cage any damp inherit rescue delay panic","0x6ce96ae5c300096b09dbd4567b0574f6a1281ae0e5cfe4f6b0233d1821f6206b"]}' http://localhost:9933
`
_{"jsonrpc":"2.0","result":null,"id":1}_

**Without Unsafe**

`
docker run -it --name polcadot --rm -v /tmp:/data:z -p 127.0.0.1:9933:9933 -p 30333:30333 parity/polkadot:master --chain westend --pruning=archive --rpc-external -d /data
`

`
curl -H 'Content-Type: application/json' -d '{"id":1, "jsonrpc":"2.0", "method": "author_insertKey", "params":["gran","favorite liar zebra assume hurt cage any damp inherit rescue delay panic","0x6ce96ae5c300096b09dbd4567b0574f6a1281ae0e5cfe4f6b0233d1821f6206b"]}' http://localhost:9933
`

_{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not _found"},"id":1}_

But we are listening 9933 port on localhost interface, it is not available outside an VM instance.
